# Generated by Django 4.2.16 on 2025-06-18 10:21

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('BIL', 'Bill'), ('ACT', 'Act'), ('REG', 'Regulation'), ('ORD', 'Order Paper'), ('SUM', 'Parliamentary Summary'), ('HAN', 'Hansard'), ('COM', 'Committee Report')], max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_path, validators=[documents.models.validate_pdf])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='documents_d_title_ccf306_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['date'], name='documents_d_date_e55297_idx')],
            },
        ),
    ]
