# Generated by Django 5.2.3 on 2025-06-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('BIL', 'Bill'), ('ACT', 'Act'), ('REG', 'Regulation'), ('ORD', 'Order Paper'), ('SUM', 'Parliamentary Summary'), ('HAN', 'Hansard'), ('COM', 'Committee Report')], max_length=3)),
                ('year', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='documents_d_title_ccf306_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['year'], name='documents_d_year_737932_idx')],
            },
        ),
    ]
