# Generated by Django 4.2.16 on 2025-06-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('BIL', 'Bills'), ('ACT', 'Acts & Ordinances'), ('REG', 'Samoa Regulations'), ('ORD', 'Order Papers'), ('SUM', 'Parliamentary Summaries'), ('HAN', 'Hansards Debates | Green Daily'), ('COM', 'Parliamentary Committee Reports'), ('Jou', 'Journals'), ('CUE', 'Cue Papers'), ('COM', 'Parliamentary Committee Reports'), ('CON', 'Constitutional Convention Debates'), ('COV', 'Government Responses'), ('GAZ', 'Western Samoa Gazettes')], max_length=3),
        ),
    ]
