# Generated by Django 4.2.16 on 2025-06-15 21:54

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdfs/%Y/%m/%d/', validators=[documents.models.validate_pdf]),
        ),
    ]
