# Generated by Django 4.2.16 on 2025-06-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file_samoan',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdfs/%Y/%m/%d/'),
        ),
    ]
