# Generated by Django 4.2.16 on 2025-06-16 01:12

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_path, validators=[documents.models.validate_pdf]),
        ),
    ]
